const settings = {
    movfmt: 'Movie Format',
    resolution: 'Resolution',
    project_fps: 'Project FPS',
    record_file_format: 'Record File Format',
    rec_proxy_file: 'Record Proxy File',
    video_encoder: 'Video Encoder',
    split_duration: 'Split Duration',
    bitrate_level: 'Bitrate Level',
    compose_mode: 'Compose Mode',
    movvfr: 'Variable Framerate',
    rec_fps: 'Playback Framrate',
    video_tl_interval: 'Video Timelapse Interval',
    enable_video_tl: 'Enable Video Timelapse',
    rec_duration: 'Record Duration',
    last_file_name: 'Last Recorded Filename',
    focus: 'Focus',
    af_mode: 'AF Mode',
    mf_drive: 'MF Drive',
    lens_zoom: 'Lens Zoom',
    ois_mode: 'OIS Mode',
    af_lock: 'AF Lock',
    lens_zoom_pos: 'Lens Zoom Position',
    lens_focus_pos: 'Lens Focus Position',
    lens_focus_spd: 'Lens Focus Speed',
    caf: 'CAF',
    caf_sens: 'CAF Sensitivity',
    live_caf: 'Live CAF',
    mf_mag: 'MF Magnify',
    restore_lens_pos: 'Restore Lens Position',
    meter_mode: 'Meter Mode',
    max_iso: 'Max ISO',
    ev_choice: 'EV',
    iso: 'ISO',
    iris: 'Iris',
    shutter_angle: 'Shutter Angle',
    max_exp_shutter_angle: 'Max EXP Shutter Angle',
    shutter_time: 'Shutter Time',
    max_exp_shutter_time: 'Max Exp Shutter Time',
    sht_operation: 'Shutter Speed/Angle',
    ae_freeze: 'AE Freeze',
    live_ae_fno: 'Live AE F-Number',
    live_ae_iso: 'Live AE ISO',
    live_ae_shutter: 'Live AE Shutter',
    live_ae_shutter_angle: 'Live AE Shutter Angle',
    wb: 'White Balance',
    mwb: 'Manual White Balance',
    tint: 'Manual White Balance Tint',
    wb_priority: 'Ambiance/White',
    mwb_r: 'Manual Whitebalance Red',
    mwb_g: 'Manual Whitebalance Green',
    mwb_b: 'Manual Whitebalance Blue',
    sharpness: 'Sharpness',
    contrast: 'Contrast',
    saturation: 'Saturation',
    brightness: 'Brightness',
    lut: 'Lookup Table',
    luma_level: 'Luma Level',
    vignette: 'Vignette',
    send_stream: 'Send Stream',
    primary_audio: 'Primary Audio',
    audio_channel: 'Audio Channel',
    audio_input_gain: 'Audio Input Gain',
    audio_output_gain: 'Audio Output Gain',
    audio_phantom_power: 'Audio Phantom Power',
    ain_gain_type: 'AGC/MGC',
    tc_count_up: 'Timecode Count Up',
    tc_hdmi_dispaly: 'Display TC on HDMI',
    tc_drop_frame: 'DF/NDF',
    assitool_display: 'Assitool Display',
    assitool_peak_onoff: 'Assitool Peak',
    assitool_peak_color: 'Assitool Peak Color',
    assitool_exposure: 'Assitool Exposure',
    assitool_zera_th1: 'Assitool Zebra High',
    assitool_zera_th2: 'Assitool Zebra Low',
    ssid: 'Wi-Fi SSID',    
    flicker: 'Flicker Reduction',
    video_system: 'Video System',
    wifi: 'Wi-Fi On',
    battery: 'Battery',
    led: 'LED On',
    lcd_backlight: 'LCD Backlight',
    hdmi_fmt: 'HDMI Format',
    hdmi_osd: 'HDMI On Screen Display',
    usb_device_role: 'USB Device Role',
    uart_role: 'UART Role',
    auto_off: 'LCD Auto Off',
    sn: 'Serial Number',
    desqueeze: 'Desqueeze',
    multiple_mode: 'Multiple Mode',
    multiple_id: 'Multiple ID',
    photosize: 'Photosize',
    photo_q: 'Photo quality',
    burst: 'Burst',
    max_exp: 'Max Exposure',
    shoot_mode: 'Shoot Mode',
    photo_tl_interval: 'Photo Timelapse Interval',
    photo_tl_num: 'Photo Timelapse Num',};
