import { writable, type Writable } from 'svelte/store';

const createStore = () => {
    const {
        subscribe,
        set,
        update,
    }: Writable<Record<string, Record<string, unknown>>> = writable({
        movfmt: undefined,
        resolution: undefined,
        project_fps: undefined,
        record_file_format: undefined,
        rec_proxy_file: undefined,
        video_encoder: undefined,
        split_duration: undefined,
        bitrate_level: undefined,
        compose_mode: undefined,
        movvfr: undefined,
        rec_fps: undefined,
        video_tl_interval: undefined,
        enable_video_tl: undefined,
        rec_duration: undefined,
        last_file_name: undefined,
        focus: undefined,
        af_mode: undefined,
        mf_drive: undefined,
        lens_zoom: undefined,
        ois_mode: undefined,
        af_lock: undefined,
        lens_zoom_pos: undefined,
        lens_focus_pos: undefined,
        lens_focus_spd: undefined,
        caf: undefined,
        caf_sens: undefined,
        live_caf: undefined,
        mf_mag: undefined,
        restore_lens_pos: undefined,
        meter_mode: undefined,
        max_iso: undefined,
        ev_choice: undefined,
        iso: undefined,
        iris: undefined,
        shutter_angle: undefined,
        max_exp_shutter_angle: undefined,
        shutter_time: undefined,
        max_exp_shutter_time: undefined,
        sht_operation: undefined,
        ae_freeze: undefined,
        live_ae_fno: undefined,
        live_ae_iso: undefined,
        live_ae_shutter: undefined,
        live_ae_shutter_angle: undefined,
        wb: undefined,
        mwb: undefined,
        tint: undefined,
        wb_priority: undefined,
        mwb_r: undefined,
        mwb_g: undefined,
        mwb_b: undefined,
        sharpness: undefined,
        contrast: undefined,
        saturation: undefined,
        brightness: undefined,
        lut: undefined,
        luma_level: undefined,
        vignette: undefined,
        send_stream: undefined,
        primary_audio: undefined,
        audio_channel: undefined,
        audio_input_gain: undefined,
        audio_output_gain: undefined,
        audio_phantom_power: undefined,
        ain_gain_type: undefined,
        tc_count_up: undefined,
        tc_hdmi_dispaly: undefined,
        tc_drop_frame: undefined,
        assitool_display: undefined,
        assitool_peak_onoff: undefined,
        assitool_peak_color: undefined,
        assitool_exposure: undefined,
        assitool_zera_th1: undefined,
        assitool_zera_th2: undefined,
        ssid: undefined,
        flicker: undefined,
        video_system: undefined,
        wifi: undefined,
        battery: undefined,
        led: undefined,
        lcd_backlight: undefined,
        hdmi_fmt: undefined,
        hdmi_osd: undefined,
        usb_device_role: undefined,
        uart_role: undefined,
        auto_off: undefined,
        sn: undefined,
        desqueeze: undefined,
        multiple_mode: undefined,
        multiple_id: undefined,
        photosize: undefined,
        photo_q: undefined,
        burst: undefined,
        max_exp: undefined,
        shoot_mode: undefined,
        photo_tl_interval: undefined,
        photo_tl_num: undefined,
    });
    return {
        subscribe,
        update,
        set,
        setValue: (ke, v) => update((prev) => ({ ...prev, [ke]: v })),
    };
};

export const cameraSettings = createStore();
